quarkus:
  application:
    name: municipality-api

  log:
    category:
      "io.smallrye.jwt":
        level: DEBUG

  http:
    port: 8080
    cors:
      ~: true
      origins: "http://localhost:4200"
      methods: GET,POST,PUT,DELETE,OPTIONS
      headers: accept,authorization,content-type,x-requested-with

    # ══════════════════════════════════════════════════════════════
    # SEGURIDAD CENTRALIZADA (Estilo Spring Security)
    # ══════════════════════════════════════════════════════════════
    auth:
      permission:
        # 1. SEGURIDAD PARA USER: Solo ADMIN puede ver lista o crear, pero todos (logueados) pueden ver su propio ID (GET)
        user-admin-access:
          paths: /api/user, /api/user/
          methods: GET, POST
          policy: admin-only
        user-details-access:
          paths: /api/user/*
          methods: GET
          policy: common-policy

        # 2. SEGURIDAD PARA SERVICE: ADMIN y USER pueden ver y crear servicios
        service-access:
          paths: /api/service/*, /api/service
          methods: GET, POST
          policy: common-policy

        # 3. SEGURIDAD PARA MUNICIPALITY (Lo que pediste anteriormente)
        municipality-common-access:
          paths: /api/municipality/*, /api/municipality
          methods: GET, POST, PUT
          policy: common-policy
        municipality-admin-only:
          paths: /api/municipality/*
          methods: DELETE
          policy: admin-only

      policy:
        common-policy:
          roles-allowed: [ ADMIN, USER ]
        admin-only:
          roles-allowed: [ ADMIN ]

  datasource:
    db-kind: postgresql
    username: ${QUARKUS_DATASOURCE_USERNAME:municipality_user}
    password: ${QUARKUS_DATASOURCE_PASSWORD:municipality_password}
    jdbc:
      url: ${QUARKUS_DATASOURCE_JDBC_URL:jdbc:postgresql://localhost:5432/municipality_db}

  hibernate-orm:
    database:
      generation: update
    sql-load-script: import.sql
    log:
      sql: false

  banner:
    path: banner.txt

# ══════════════════════════════════════════════════════════════
# MICROPROFILE & JWT CONFIGURATION
# ══════════════════════════════════════════════════════════════
mp:
  jwt:
    verify:
      publickey:
        location: public.pem
      issuer: auth-api
    token:
      header: Authorization

smallrye:
  jwt:
    path:
      groups: roles # Esto busca el array "roles" en el JWT que genera tu auth-api

  openapi:
    extensions:
      smallrye:
        info:
          title: "Municipality API"
          version: "1.0.0"
          description: "API for the management of municipalities"